site_name: Material de LEI
site_url: https://darteescar.github.io/LEI-Material-Estudo/

theme:
  name: material
  palette:
    primary: deep purple
    accent: purple
    scheme: slate
  language: pt
  logo: assets/livro.png
  favicon: assets/livro.png

nav:
  - Início: index.md

extra:
  analytics: 
    provider: google
    property: G-M15LQD5QPZ
    feedback:
      title: Achas-te a página útil?
      ratings:
        - icon: material/thumb-up-outline
          name: Esta página foi útil
          data: 1
          note: >-
            Obrigado pelo teu feedback!
        - icon: material/thumb-down-outline
          name: Esta página podia ser melhorada
          data: 0
          note: >- 
            Obrigado pelo teu feedback!