site_name: Material de LEI
theme:
  name: material
  palette:
    primary: deep purple
    accent: purple
    scheme: slate
    language: pt
    logo: assets/livro.png
    favicon: assets/livro.png

nav:
  - In√≠cio: index.md